### DISCUSSION TITLE
Can I run `zstash` without `conda`?

### DISCUSSION THREAD

**Discussion by forsyth2** [E3SM-Project/zstash#287] [Questions]
Asked by @ndkeen. #288 also records the suggestion for a stand-alone mode.

**Comment by forsyth2** [comment]
Suggestions from @mahf708:

- https://github.com/conda-forge/zstash-feedstock/blob/main/recipe/meta.yaml#L14:

```
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six
    - globus-sdk >=3.0.0,<4.0.0
    - fair-research-login >=0.2.6,<0.3.0
```

- "This means you need a python above 3.6 and the three dependencies available at runtime (note that you can likely get these from anywhere, e.g., PyPI). If you do python -m pip install . in the root of the zstash repo, pip will get them for you from pypi"

- dependencies "were removed from zstash repo. Please do the following as an extra step (before/after): `python -m pip install 'globus-sdk>=3.0.0,<4.0.0' 'fair-research-login>=0.2.6,<0.3.0`".

- Users can refer to https://e3sm-project.github.io/zstash/_build/html/main/tutorial.html (this uses an older version of zstash), following the non-HPSS steps.
